let languages = {
    es: {
        m: 'Masas',
        m_s: 'Masa Soluto',
        m_d: 'Masa Disolvente',
        m_D: 'Masa Disolución',
        v: 'Volúmenes',
        v_s: 'Volumen Soluto',
        v_d: 'Volumen Disolvente',
        v_D: 'Volumen Disolución',
        d: 'Densidades',
        d_s: 'Densidad Soluto',
        d_d: 'Densidad Disolvente',
        d_D: 'Densidad Disolución',
        p_m: '% Masa',
        p_v: '% Volumen',
        c: 'Concentración',
        molaridad: 'Molaridad',
        molalidad: 'Molalidad',
        m_mol: 'Masas Molares',
        m_mol_s: 'Masa Molar Soluto',
        m_mol_d: 'Masa Molar Disolvente',
        m_mol_D: 'Masa Molar Disolución',
        f_m: 'Fracción Molar',
        n: 'Número de Moles',
        n_s: 'Moles Soluto',
        n_d: 'Moles Disolvente',
        n_D: 'Moles Disolución',
        v_a: 'Volúmenes Aditivos',
        redondeo: 'Redondeo',
        notation: 'Notación',
        language: 'Idioma',
    },
    en: {
        m: 'Masses',
        m_s: 'Solute Mass',
        m_d: 'Solvent Mass',
        m_D: 'Solution Mass',
        v: 'Volumes',
        v_s: 'Solute Volume',
        v_d: 'Solvent Volume',
        v_D: 'Solution Volume',
        d: 'Densities',
        d_s: 'Solute Density',
        d_d: 'Solvent Density',
        d_D: 'Solution Density',
        p_m: '% Mass',
        p_v: '% Volume',
        c: 'Concentration',
        molaridad: 'Molarity',
        molalidad: 'Molality',
        m_mol: 'Molar Nasses',
        m_mol_s: 'Solute Molar Mass',
        m_mol_d: 'Solvent Molar Mass',
        m_mol_D: 'Solution Molar Mass',
        f_m: 'Molar Fraction',
        n: 'Number of Moles',
        n_s: 'Moles Solute',
        n_d: 'Moles Solvent',
        n_D: 'Moles Solution',
        v_a: 'Additive Volumes',
        redondeo: 'Rounding',
        notation: 'Notation',
        language: 'Language',
    }
}