let languages = {
    es: {
        m: 'Masas',
        m_s: 'Masa soluto',
        m_d: 'Masa disolvente',
        m_D: 'Masa disolución',
        v: 'Volúmenes',
        v_s: 'Volumen soluto',
        v_d: 'Volumen disolvente',
        v_D: 'Volumen disolución',
        d: 'Densidades',
        d_s: 'Densidad soluto',
        d_d: 'Densidad disolvente',
        d_D: 'Densidad disolución',
        p_m: '% Masa',
        p_v: '% Volumen',
        c: 'Concentración',
        molaridad: 'Molaridad',
        molalidad: 'Molalidad',
        m_mol: 'Masas Molares',
        m_mol_s: 'Masa molar soluto',
        m_mol_d: 'Masa molar disolvente',
        m_mol_D: 'Masa molar disolución',
        f_m: 'Fracción molar',
        n: 'Número de Moles',
        n_s: 'Número moles soluto',
        n_d: 'Número moles disolvente',
        n_D: 'Número moles disolución',
        v_a: 'Volúmenes Aditivos',
        redondeo: 'Redondeo',
        notation: 'Notación',
        language: 'Idioma',
    },
    en: {
        m: 'Masses',
        m_s: 'Solute mass',
        m_d: 'Solvent mass',
        m_D: 'Solution mass',
        v: 'Volumes',
        v_s: 'Solute volume',
        v_d: 'Solvent volume',
        v_D: 'Solution volume',
        d: 'Densities',
        d_s: 'Solute density',
        d_d: 'Solvent density',
        d_D: 'Solution density',
        p_m: '% Mass',
        p_v: '% Volume',
        c: 'Concentration',
        molaridad: 'Molarity',
        molalidad: 'Molality',
        m_mol: 'Molar masses',
        m_mol_s: 'Solute molar mass',
        m_mol_d: 'Solvent molar mass',
        m_mol_D: 'Solution molar mass',
        f_m: 'Molar fraction',
        n: 'Number of Moles',
        n_s: 'Number moles solute',
        n_d: 'Number moles solvent',
        n_D: 'Number moles solution',
        v_a: 'Additive volumes',
        redondeo: 'Rounding',
        notation: 'Notation',
        language: 'Language',
    }
}